### ISSUE TITLE
removeExpiredMember test case fails in CI environment

### ISSUE THREAD

**Issue by qswawrq** [usdot-fhwa-stol/CARMAPlatform#184]
### Descriptive summary
```One test case might fail in PlatoonManagerTest class.
gov.dot.fhwa.saxton.carma.plugins.platooning.PlatoonManagerTest > removeExpiredMember FAILED
    java.lang.AssertionError: expected:<2> but was:<1>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:631)
        at gov.dot.fhwa.saxton.carma.plugins.platooning.PlatoonManagerTest.removeExpiredMember(PlatoonManagerTest.java:73)```
### Expected behavior
This test should pass reliably in the both development environment and testing environment.
### Actual behavior
It fails with some possibility on Circle CI.
### Steps to reproduce the behavior
Run build/test for the current develop branch on CI for 10 times. It will show up as a failed test case.
### Related work
N/A

**Comment by msmcconnell** [comment]
Resolved by PR #183
